### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ggebbie** [ggebbie/BLUEs.jl#1]
- [x] error propagation a la `Measurements.jl` for vectors with correlation
- [x] `Problem` struct a la `LinearSolve.jl`
- [x] make struct types more concrete to help performance
- [x] Underdetermined problems
- [ ] Measurements not keeping solution/error significant digits consistent
- [x] permit weighting matrices to be vectors that describe diagonal
- [x] optional calculate cost in `solve`
- [ ] check performance of inner products, allow quick inner product when weighted by a diagonal matrix
- [ ] replace weighting matrices with Cholesky factorizations
- [x] permit NamedTuple Estimate, pass this Estimate to `solve`
- [x] permit NamedTuple Estimate with covariance between fields, explore `BlockFactorizations` for operations/(*)
- [x] permit scalar (not vector) Estimate
- [x] Multiple observational matrices in a NamedTuple
- [x] do tests for dimensionless problems
